language: java
jdk:
  - oraclejdk8

secure:
  # Test secret
  - "rm/QCLsqKYosUPwKautm+zsMOTS2ZeQh81D3W41OZjNDcp6w/FSNcubZYQedTmgRBR071CUBwklOm+Sjwof4vQFY5AEtsUAkZayhZNkBPr99ZFotFdkyhPTC8n7Tju1453JT1NqrIGDw6dRVxNEZhmON+3J2j7GyvL45u6PRLMEUmhAlGWLtc/Npv5uPGS7uLEFqq5x1UP4IysIwdFKsX5NhcU7AkcEUsRudnZU32XuVC3UN2vdjG9JOpuycudWC/kNG/2l4WEwimMEtyPhBue4vNtXSm5hkTFzt7v7G80mEd5nI84nrBtq+1AHPKi1+3ULq7HA3/E+V0+XuBIpWI8HoFWSbxFJaSwsDiCfJLTzCTAJvEkSZq+rvc1vXmVu9KdpDKyPKD8S+bqDVKPEZDuAtExTKdAZIj0mm+8YBi6ZOcbMQJRAivPbJXyph7M3TSb99kReLVyzauldBT6595e5TD04cQdK0hdm818Q2n3F6WaEDQ8iDU83W42kyaH1AckiTQt5pokZ/1lvv+yn+p8FjRXIYY/buZWT/YVI9ziHlLtFWLlrSPEYRYNFkYNIbuLhglFQy26hpi5xLxivBb0CSbAM96eEi+EqiPIiTVDFahgXzglBidHIiWwdpdGv3Zj0H3J+/HhF569JabzS5vtsG0/XRbCT4a40+n7QIaU4="

install:
  - whoami
  - pwd
  - ls -la
  - printenv
  - uname -a
  - lsb_release -a
  - df -h
  - mount

script:
  - mvn -v
  - cd spring-boot-helloworld
  - mvn install
  - printenv
  - ls -la target
