version: 0.2

env:
  variables:
    testvar: "foobar"

phases:
  install:
    commands:
      - whoami
      - pwd
      - ls -la
      - printenv
      - uname -a
      - lsb_release -a
      - df -h
      - mount
  pre_build:
    commands:
      - mvn -v
  build:
    commands:
      - cd spring-boot-helloworld
      - mvn install
  post_build:
    commands:
      - printenv
      - ls -la target

#artifacts:
#  files:
#    - location
#    - location
#  discard-paths: yes
#  base-directory: location

#cache:
#  paths:
#    - path
#    - path
